/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import dao.DAO;
import java.util.List;
import javax.swing.JOptionPane;
import model.Detail;
import model.Material;
import model.Product;
import tablemodels.DetailTableModel;
import tablemodels.ProductTableModel;

/**
 *
 * @author user
 */
public class productFrame extends javax.swing.JFrame {

    /**
     * Creates new form productFrame
     */
    ProductTableModel prodModel;
    DetailTableModel detailTableModel;
    DAO dao;
    List<Product> products; 
    
    public productFrame() {
        products = null;
        
        dao = new DAO();
        products = dao.getAllProducts();
        this.prodModel = new ProductTableModel(products);
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTableProduct = new javax.swing.JTable();
        jButtonSelectMaterials = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableDetails = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButtonMaterial = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jButtonMatGetDetail = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldMaterialName = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Обозреватель часов");

        jTableProduct.setModel(prodModel);
        jScrollPane1.setViewportView(jTableProduct);

        jButtonSelectMaterials.setText("Показать детали");
        jButtonSelectMaterials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSelectMaterialsActionPerformed(evt);
            }
        });

        jTableDetails.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane2.setViewportView(jTableDetails);

        jLabel1.setText("Список часов:");

        jButtonMaterial.setText("Показать материалы");
        jButtonMaterial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMaterialActionPerformed(evt);
            }
        });

        jLabel2.setText("Детали из, которых состоят выделенные часы:");

        jButtonMatGetDetail.setText("Узнать материал, выделенной детали");
        jButtonMatGetDetail.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMatGetDetailActionPerformed(evt);
            }
        });

        jLabel3.setText("Имя материала:");

        jTextFieldMaterialName.setEditable(false);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButtonSelectMaterials)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonMaterial)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButtonMatGetDetail))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 571, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel2)))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSelectMaterials)
                    .addComponent(jButtonMaterial)
                    .addComponent(jButtonMatGetDetail))
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldMaterialName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(52, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSelectMaterialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSelectMaterialsActionPerformed
        try{
        int indexRow = jTableProduct.getSelectedRow();
        ProductTableModel prodModel = (ProductTableModel) jTableProduct.getModel();
        int idProduct = Integer.parseInt(prodModel.getValueAt(indexRow, 0).toString());
        
        List<Detail> listDetails = dao.getDetailByProductId(idProduct);
        detailTableModel = new DetailTableModel(listDetails);
        jTableDetails.setModel(detailTableModel);
        //OrderTableModel ordModel = (OrderTableModel) jTableOrder.getModel();
        } catch(ArrayIndexOutOfBoundsException  ex){
             JOptionPane.showMessageDialog(null, "В начале нужно выделить элемент: " + ex, "Выделите изделие", 1);
        }
    }//GEN-LAST:event_jButtonSelectMaterialsActionPerformed

    private void jButtonMatGetDetailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMatGetDetailActionPerformed
        try{
            int indexRow = jTableDetails.getSelectedRow();
            int idMaterial = detailTableModel.getMaterialId(indexRow);
            Material material = dao.getMaterialById(idMaterial);
            jTextFieldMaterialName.setText(material.getName());
        } catch(NullPointerException ex){
            JOptionPane.showMessageDialog(null, "В начале нужно выделить деталь: " + ex.getMessage(), "Ошибка", 1);
        } catch(ArrayIndexOutOfBoundsException ex) {
             JOptionPane.showMessageDialog(null, "В начале нужно выделить деталь: " + ex, "Выделите деталь", 1);
        }
        //System.out.println(idMaterial);
    }//GEN-LAST:event_jButtonMatGetDetailActionPerformed

    private void jButtonMaterialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMaterialActionPerformed
            try {
                MaterialsJFrame mf = new MaterialsJFrame();
                mf.setVisible(true);
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "В начале нужно выделить деталь: " + ex.getMessage(), "Ошибка", 1);
            }
    }//GEN-LAST:event_jButtonMaterialActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(productFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new productFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonMatGetDetail;
    private javax.swing.JButton jButtonMaterial;
    private javax.swing.JButton jButtonSelectMaterials;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableDetails;
    private javax.swing.JTable jTableProduct;
    private javax.swing.JTextField jTextFieldMaterialName;
    // End of variables declaration//GEN-END:variables
}
